library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Top-level entity flashed to the DE10-Lite.
-- This single entity contains EVERYTHING needed to drive the VGA from a
-- 50 MHz oscillator and a reset button :
--   * clk_divider     : 50 MHz -> 25 MHz pixel clock
--   * IP_ROM          : Quartus-generated ROM (altsyncram, 65536 x 12 bits)
--                       initialized from PERROQUET.mif
--   * HSYNC_COUNT     : horizontal pixel counter
--   * VSYNC_COUNT     : vertical line counter
--   * COMPARATOR_HSYNC: generates VGA_HS
--   * COMPARATOR_VSYNC: generates VGA_VS
--   * COMPARATOR_TDISP: tells RGB_OUTPUT when we are in the visible area
--   * RGB_OUTPUT      : computes the ROM address and drives the VGA colours
--
-- IMPORTANT for synthesis :
--   * IP_ROM.vhd is generated by Quartus IP Catalog (ROM 1-PORT, altsyncram).
--     It lives in the Quartus project folder and is NOT versioned in git.
--   * The PERROQUET.mif file must be reachable at the path configured in
--     the IP (see init_file generic inside IP_ROM.vhd).
--   * Set the device configuration mode to "Single Uncompressed Image with
--     Memory Initialization" in Assignments -> Device -> Device and Pin
--     Options -> Configuration, otherwise Quartus will reject the design
--     with Error (14703).
--
-- For SIMULATION with GHDL :
--   * A behavioural IP_ROM mock lives in sim/IP_ROM.vhd ; it has the same
--     entity interface but reads pixel = address(11 downto 0). Quartus
--     ignores that file because it is not added to the project.
--
-- DE10-Lite pin mapping (to be applied in the .qsf file) :
--   MAX10_CLK1_50 -> P11   (50 MHz oscillator)
--   KEY[0]        -> B8    (push button, active low -> wired to nRST)
--   VGA_R[3..0]   -> A9, B10, C9, A5
--   VGA_G[3..0]   -> L7, K7, J7, J8
--   VGA_B[3..0]   -> B6, B7, A7, A8
--   VGA_HS        -> N3
--   VGA_VS        -> N1
entity VGA_DISPLAY_RAM is
    generic (
        IMG_WIDTH  : integer := 256;
        IMG_HEIGHT : integer := 256;
        ADDR_BITS  : integer := 16
    );
    Port (
        MAX10_CLK1_50 : in  STD_LOGIC;
        KEY0          : in  STD_LOGIC;
        VGA_R         : out STD_LOGIC_VECTOR(3 downto 0);
        VGA_G         : out STD_LOGIC_VECTOR(3 downto 0);
        VGA_B         : out STD_LOGIC_VECTOR(3 downto 0);
        VGA_HS        : out STD_LOGIC;
        VGA_VS        : out STD_LOGIC
    );
end VGA_DISPLAY_RAM;

architecture Behavioral of VGA_DISPLAY_RAM is

    -- ---------------------------------------------------------------------
    -- Component declarations
    -- ---------------------------------------------------------------------

    component clk_divider
        Port (
            CLK_50 : in  STD_LOGIC;
            CLK_25 : out STD_LOGIC
        );
    end component;

    -- Quartus-generated ROM IP (altsyncram, ROM mode, 65536 x 12 bits,
    -- initialized from PERROQUET.mif).
    -- The component declaration must match the entity in IP_ROM.vhd
    -- (Quartus project for synthesis, sim/ folder for simulation).
    component IP_ROM
        Port (
            address : in  STD_LOGIC_VECTOR(15 downto 0);
            clock   : in  STD_LOGIC;
            q       : out STD_LOGIC_VECTOR(11 downto 0)
        );
    end component;

    component HSYNC_COUNT is
        port(
            CLK              : in  STD_LOGIC;
            nRST             : in  STD_LOGIC;
            HCOUNT_OVERFLOW  : out STD_LOGIC;
            HCOUNTER_VALUE   : out STD_LOGIC_VECTOR(9 downto 0)
        );
    end component;

    component VSYNC_COUNT is
        port(
            CLK              : in  STD_LOGIC;
            nRST             : in  STD_LOGIC;
            HCOUNT_OVERFLOW  : in  STD_LOGIC;
            VCOUNTER_VALUE   : out STD_LOGIC_VECTOR(9 downto 0)
        );
    end component;

    component COMPARATOR_HSYNC is
        port(
            CLK              : in  STD_LOGIC;
            nRST             : in  STD_LOGIC;
            HCOUNTER_VALUE   : in  STD_LOGIC_VECTOR(9 downto 0);
            H_SYNC           : out STD_LOGIC
        );
    end component;

    component COMPARATOR_VSYNC is
        port(
            CLK              : in  STD_LOGIC;
            nRST             : in  STD_LOGIC;
            VCOUNTER_VALUE   : in  STD_LOGIC_VECTOR(9 downto 0);
            V_SYNC           : out STD_LOGIC
        );
    end component;

    component COMPARATOR_TDISP is
        port(
            CLK              : in  STD_LOGIC;
            nRST             : in  STD_LOGIC;
            HCOUNTER_VALUE   : in  STD_LOGIC_VECTOR(9 downto 0);
            VCOUNTER_VALUE   : in  STD_LOGIC_VECTOR(9 downto 0);
            DISPLAY_SIGNAL   : out STD_LOGIC
        );
    end component;

    component RGB_OUTPUT is
        generic(
            IMG_WIDTH  : integer := 256;
            IMG_HEIGHT : integer := 256;
            ADDR_BITS  : integer := 16
        );
        Port (
            CLK              : in  STD_LOGIC;
            nRST             : in  STD_LOGIC;
            DISPLAY_SIGNAL   : in  STD_LOGIC;
            HCOUNTER_VALUE   : in  STD_LOGIC_VECTOR(9 downto 0);
            VCOUNTER_VALUE   : in  STD_LOGIC_VECTOR(9 downto 0);
            DATA             : in  STD_LOGIC_VECTOR(11 downto 0);
            ADDRESS          : out STD_LOGIC_VECTOR(ADDR_BITS - 1 downto 0);
            VGA_R            : out STD_LOGIC_VECTOR(3 downto 0);
            VGA_G            : out STD_LOGIC_VECTOR(3 downto 0);
            VGA_B            : out STD_LOGIC_VECTOR(3 downto 0)
        );
    end component;

    -- ---------------------------------------------------------------------
    -- Internal signals
    -- ---------------------------------------------------------------------
    signal clk_25mhz         : STD_LOGIC;
    signal s_DISPLAY_SIGNAL  : STD_LOGIC;
    signal s_HCOUNTER_VALUE  : STD_LOGIC_VECTOR(9 downto 0);
    signal s_VCOUNTER_VALUE  : STD_LOGIC_VECTOR(9 downto 0);
    signal s_HCOUNT_OVERFLOW : STD_LOGIC;
    signal s_RAM_ADDR        : STD_LOGIC_VECTOR(ADDR_BITS - 1 downto 0);
    signal s_RAM_DATA        : STD_LOGIC_VECTOR(11 downto 0);

begin

    -- 50 MHz -> 25 MHz pixel clock
    u_clk_div : clk_divider
        port map (
            CLK_50 => MAX10_CLK1_50,
            CLK_25 => clk_25mhz
        );

    -- ROM with the image
    u_rom : IP_ROM
        port map (
            address => s_RAM_ADDR,
            clock   => clk_25mhz,
            q       => s_RAM_DATA
        );

    -- Horizontal counter
    u_hsync_count : HSYNC_COUNT
        port map (
            CLK             => clk_25mhz,
            nRST            => KEY0,
            HCOUNT_OVERFLOW => s_HCOUNT_OVERFLOW,
            HCOUNTER_VALUE  => s_HCOUNTER_VALUE
        );

    -- Vertical counter (advances on each HSYNC overflow)
    u_vsync_count : VSYNC_COUNT
        port map (
            CLK             => clk_25mhz,
            nRST            => KEY0,
            HCOUNT_OVERFLOW => s_HCOUNT_OVERFLOW,
            VCOUNTER_VALUE  => s_VCOUNTER_VALUE
        );

    -- Horizontal sync pulse generator
    u_comp_hsync : COMPARATOR_HSYNC
        port map (
            CLK             => clk_25mhz,
            nRST            => KEY0,
            HCOUNTER_VALUE  => s_HCOUNTER_VALUE,
            H_SYNC          => VGA_HS
        );

    -- Vertical sync pulse generator
    u_comp_vsync : COMPARATOR_VSYNC
        port map (
            CLK             => clk_25mhz,
            nRST            => KEY0,
            VCOUNTER_VALUE  => s_VCOUNTER_VALUE,
            V_SYNC          => VGA_VS
        );

    -- Visible-area detector
    u_comp_tdisp : COMPARATOR_TDISP
        port map (
            CLK             => clk_25mhz,
            nRST            => KEY0,
            HCOUNTER_VALUE  => s_HCOUNTER_VALUE,
            VCOUNTER_VALUE  => s_VCOUNTER_VALUE,
            DISPLAY_SIGNAL  => s_DISPLAY_SIGNAL
        );

    -- RGB output : computes the ROM address and gates the pixel colours
    -- KEY0 is the active-low reset button on the DE10-Lite ; wired
    -- directly into the active-low nRST inputs of every sub-module.
    u_rgb : RGB_OUTPUT
        generic map (
            IMG_WIDTH  => IMG_WIDTH,
            IMG_HEIGHT => IMG_HEIGHT,
            ADDR_BITS  => ADDR_BITS
        )
        port map (
            CLK             => clk_25mhz,
            nRST            => KEY0,
            DISPLAY_SIGNAL  => s_DISPLAY_SIGNAL,
            HCOUNTER_VALUE  => s_HCOUNTER_VALUE,
            VCOUNTER_VALUE  => s_VCOUNTER_VALUE,
            DATA            => s_RAM_DATA,
            address         => s_RAM_ADDR,
            VGA_R           => VGA_R,
            VGA_G           => VGA_G,
            VGA_B           => VGA_B
        );

end Behavioral;
