library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

-- Behavioural MOCK of the Quartus IP_ROM, used ONLY in simulation.
-- The real IP_ROM.vhd is generated by Quartus (altsyncram) and lives in
-- the Quartus project folder ; it requires the altera_mf library that
-- GHDL does not have.
--
-- This mock keeps the same entity name and port signature so the testbench
-- can compile and link without modifying VGA_DISPLAY_RAM.
--
-- Behaviour : combinational read where DATA = address(11 downto 0).
-- That is enough to verify the timing connectivity of the design ; the
-- real image content is validated on a physical VGA screen.
entity IP_ROM is
    Port (
        address : in  STD_LOGIC_VECTOR(15 downto 0);
        clock   : in  STD_LOGIC;
        q       : out STD_LOGIC_VECTOR(11 downto 0)
    );
end IP_ROM;

architecture sim of IP_ROM is
begin
    q <= address(11 downto 0);
end sim;
